development:
  adapter: mysql2
  encoding: utf8
  database: tz_development
  pool: 5
  username: root
  password: 2510412
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  database: tz_test
  pool: 5
  username: root
  password: 2510412
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  database: tz_production
  pool: 5
  username: root
  password: 2510412
  socket: /var/run/mysqld/mysqld.sock
